### ISSUE TITLE
Brightness control?

### ISSUE THREAD

**Issue by gtoal** [amaiorano/vectrexy#11]
I was trying the new "Raid under vectrexia" rom and it says 'adjust the brightness until the image below is dark but just visible'.  Unfortunately under Vectrexy it is completely black and there's no control to increase the brightness.

**Comment by amaiorano** [comment]
Thanks, Graham, I'll check it out. It does look like the game works fine when you play it, though, right?

**Comment by gtoal** [comment]
Well, it runs but with some of the graphics not visible so I'm not sure I'd go as far as 'works fine'.  It would be like playing Pacman with invisible dots... - if critical information is missing you can't play effectively.  I'm not particularly worried about not playing this particular game, I was more interested in having your emulator support accurate emulation.  It would be improved by having a brightness control, especially if the brightness applies across different levels of intensity and lets you control the cutoff point where images disappear entirely.  Even down to the level where flyback traces might be visible when turned fully up.

**Comment by amaiorano** [comment]
I'll investigate. I'm not sure if I'll expose a brightness control, given that this exists on the real hardware mainly because they could not guarantee a fixed brightness across all units. But first, I'll see why it's not rendering properly.

**Comment by amaiorano** [comment]
I've added a "brightness curve" option in the config menu. The default value of 0 is the default, which maps the brightess values linearly. You can slide it up to 1, which maps the brightess to a "ease in" curve, basically making the lower values brighter (and higher values show less difference in brightness). Please give it a shot.

**Comment by gtoal** [comment]
Excellent! That fixed it.
