### ISSUE TITLE
Vectors do not draw on my system

### ISSUE THREAD

**Issue by gtoal** [amaiorano/vectrexy#2]
The program appears to start and run on my Windows10 Home (on an HP portable) but no vectors are drawn.  However the overlays *are* drawn.  Let me know what information/testing you need to narrow this down.

**Comment by amaiorano** [comment]
Hi Graham,

First, thanks for trying it out! Okay, a couple questions:
1. Which version did you try, 64 or 32 bit?
2. Can you share the output in the console window that opens? Maybe there's a clue to what's going on there.

Thanks!

**Comment by gtoal** [comment]
64 bit.  I'm invoking it from within the directory where I unpacked it:
C:\Users\root\Downloads\Vector Emulation\vectrexy_win64

Console window says:
Root path set to: C:\Users\root\Downloads\Vector Emulation\vectrexy_win64
Found overlay for Minestorm: C:\Users\root\Downloads\Vector Emulation\vectrexy_win64\overlays\1_libretro\Mine_Storm.png
Found overlay for C:\Users\root\Downloads\Vector Emulation\vectrexy_win64\roms\Scramble (1982).vec: C:\Users\root\Downloads\Vector Emulation\vectrexy_win64\overlays\1_libretro\Scramble.png

It reports between 130 and 170 FPS.

**Comment by gtoal** [comment]
And the emulation is definitely running - as can be seen from checking the trace:
$02cc (c)>trace
[$09c8] 271a       BEQ $1a                          (26), PC + offset = $09e4                 3 A$00|B$08|X$00f0|Y$c888|U$c8c3|S$cbe4|DP$c8|eFHInzvc
[$09ca] 1f01       TFR D,X                                                                    6 A$00|B$08|X$0008|Y$c888|U$c8c3|S$cbe4|DP$c8|eFHInzvc
[$09cc] 84c0       ANDA #$c0                        (192)                                     2 A$00|B$08|X$0008|Y$c888|U$c8c3|S$cbe4|DP$c8|eFHInZvc
[$09ce] 270a       BEQ $0a                          (10), PC + offset = $09da                 3 A$00|B$08|X$0008|Y$c888|U$c8c3|S$cbe4|DP$c8|eFHInZvc
[$09da] 1f10       TFR X,D                                                                    6 A$00|B$08|X$0008|Y$c888|U$c8c3|S$cbe4|DP$c8|eFHInZvc
[$09dc] 58         LSLB/ASLB                                                                  2 A$00|B$10|X$0008|Y$c888|U$c8c3|S$cbe4|DP$c8|eFHInzvc
[$09dd] 48         LSLA/ASLA                                                                  2 A$00|B$10|X$0008|Y$c888|U$c8c3|S$cbe4|DP$c8|eFhInZvc
[$09de] 1f01       TFR D,X                                                                    6 A$00|B$10|X$0010|Y$c888|U$c8c3|S$cbe4|DP$c8|eFhInZvc
[$09e0] ad9f       JSR [$c8ec]                      $09e2->$c8 $09e3->$ec $c8ec->$2 $c8ed->$ca $cbe3<-$e4 $cbe2<-$9 12 A$00|B$10|X$0010|Y$c888|U$c8c3|S$cbe2|DP$c8|eFhInZvc
[$02ca] 3436       PSHS A,B,X,Y                     #$36 (54) $cbe1<-$88 $cbe0<-$c8 $cbdf<-$10 $cbde<-$0 $cbdd<-$10 $cbdc<-$0 11 A$00|B$10|X$0010|Y$c888|U$c8c3|S$cbdc|DP$c8|eFhInZvc
$02cc (trace)>

**Comment by gtoal** [comment]
Version.txt contains: v0.0.0-452-g344aed3

**Comment by amaiorano** [comment]
Do you know what kind of video card you have?

**Comment by gtoal** [comment]
AMD Radeon R5

**Comment by gtoal** [comment]
HP Pavilion Notebook (B&O branded sound)
AMD A8-7410 APU 2.20GHz
64 bit O/S

**Comment by amaiorano** [comment]
Okay, can I ask you to open the file "options.txt" that should be in the root folder where you extracted Vectrexy, and set ```enableGLDebugging = true```. Then run Vectrexy and share the output in the console window? It's possible that it might spam a lot; if so, try running the emulator and immediately hitting Ctrl+Break to go to the debugger, at which point it will stop spamming and you can copy the output.

Thank you again!

**Comment by gtoal** [comment]
This is weird. I changed the line you asked me to and saved: this is what the file looks like now:
enableGLDebugging = true
imguiDebugWindow = false
imguiFontScale = 1.000000
lastOpenedFile = C:\Users\root\Downloads\Vector Emulation\vectrexy_win64\roms\Scramble (1982).vec
windowHeight = -1
windowMaximized = false
windowWidth = -1
windowX = 708
windowY = 46

and restarted the program - I see no new debugging info!

C:\Users\root\Downloads\Vector Emulation\vectrexy_win64>vectrexy
Root path set to: C:\Users\root\Downloads\Vector Emulation\vectrexy_win64
Found overlay for Minestorm: C:\Users\root\Downloads\Vector Emulation\vectrexy_win64\overlays\1_libretro\Mine_Storm.png
Found overlay for C:\Users\root\Downloads\Vector Emulation\vectrexy_win64\roms\Scramble (1982).vec: C:\Users\root\Downloads\Vector Emulation\vectrexy_win64\overlays\1_libretro\Scramble.png

I also tried it by opening a command window, cd'iong to the directory and starting it as a command-line. No difference from double clicking or dropping a rom file on the exe.

**Comment by amaiorano** [comment]
Okay, it's not that weird. That option will only output OpenGL errors/warnings returned by the driver, if there are any. I'm not sure why it's not working. You could try playing around with some of the GLRender options in the Debug -> Debug Window dialog:

![image](https://user-images.githubusercontent.com/6893883/43676722-94d1fecc-97c4-11e8-97f6-f4ea405a7021.png)

Maybe toggle EnableMaxTextureSize, or ThickBaseLines.

I'm going to test out Vectrexy on different machines I have access to and see if I can reproduce this myself.

Thanks.

**Comment by gtoal** [comment]
possibly another clue: it is also completely silent.  No startup sounds or game sounds at all.  PC Volume is up and sound is enabled.

**Comment by gtoal** [comment]
While I was tweaking the graphics parameters (just a little to see if any change caused the graphics to start) this happened:

Root path set to: C:\Users\root\Downloads\Vector Emulation\vectrexy_win64
Found overlay for Minestorm: C:\Users\root\Downloads\Vector Emulation\vectrexy_win64\overlays\1_libretro\Mine_Storm.png
Exception caught:
Assertion Failed!
 Condition: result == 0b110
 File: c:\projects\vectrexy\src\via.cpp(54)
 Message: ShiftRegisterMode expected to only support ShiftOutUnder02

[$e0f0] 0f3b       CLR $3b                          DP:(PC) = $d03b $d03b<-$0                99999 A$3f|B$ff|X$c83f|Y$cb0b|U$cbeb|S$cbea|DP$d0|eFHInzvC
$e0f2 (step)>

that was about 20 seconds after starting Minestorm.

**Comment by gtoal** [comment]
![image](https://user-images.githubusercontent.com/8899318/43677791-bb24d1c2-97cd-11e8-913e-44ba14001ee5.png)
Note my debug window doesn't have all the options that yours does.

**Comment by gtoal** [comment]
I just now installed v0.0.0-510-gf0e34ad in a separate directory, and it works...

**Comment by gtoal** [comment]
Also pleased to note that my Tailgunner rom which is > 32K works correctly!

**Comment by amaiorano** [comment]
So the original version you trying to run was v0.0.0-452-g344aed3. Was this a version you had downloaded from GitHub a while ago? I should have checked when you told me the version as this was an older version, for sure. In fact, the very next commit after 344aed3, I fixed a bug that caused the blank screen error for some people. I really should have looked.

I'm very happy the latest version is working for you :) And I'm glad Tailgunner works as well!

**Comment by gtoal** [comment]
I downloaded it the day you posted on Vectrex Fans Unite! that you had added support for 48K roms.  Sorry it took me so long to get around to proper testing - sometimes life intervenes.

**Comment by amaiorano** [comment]
No worries! I know very well about life intervening 😀
