### ISSUE TITLE
Embed version number in code, not just in version.txt?

### ISSUE THREAD

**Issue by gtoal** [amaiorano/vectrexy#3]
Got this error playing Omega Chase just now:

Root path set to: C:\Users\root\Downloads\Vector Emulation\vectrexy_latest
Found overlay for C:\Users\root\Downloads\Vector Emulation\vectrexy_latest\roms\Omega Chase (Final Version) (1998) (PD).vec: C:\Users\root\Downloads\Vector Emulation\vectrexy_latest\overlays\2_vectrexworld\Omega Chase (Final Version) (1998) (PD).png
Exception caught:
Assertion Failed!
 Condition: false
 File: c:\projects\vectrexy\src\via.cpp(318)
 Message: A without handshake not implemented yet

[$3e96] dcde       LDD $de                          DP:(PC) = $d0de $d0de->$0                99999 A$01|B$40|X$071a|Y$ca4d|U$ca6b|S$cbe6|DP$d0|eFHInzvc
$3e98 (step)>

It might be helpful to you to print the version number of the build with this information?

(btw it was v0.0.0-510-gf0e34ad )

**Comment by amaiorano** [comment]
Yes, I have a plan to modify these types of errors from asserts, which halt the emulator, to use my "unsupported" function, which will either ignore/log/fail depending on a certain option. Many of these unsupported features don't really matter for most games. In this case, you can trying entering 'c' for continue in the debugger, and if it stops again, just keep pressing (or holding) Enter for it to keep continuing. Sometimes that's enough to get past the bit of code that is using the unsupported feature.

**Comment by amaiorano** [comment]
Also, to actually address the issue you created here, right now when there's a problem like this, it breaks into the debugger. This is mostly a development feature, not a release feature, so I'm not sure I want to print the version number there. Eventually, I was planning to make a proper release version of the emulator without the debugger, and in that case, I would likely show a message with the version, and generate a log file that could be sent to me.

**Comment by amaiorano** [comment]
Closing this as there's nothing to do for now.
