### ISSUE TITLE
GCE Test Rom V4 breaks into debugger

### ISSUE THREAD

**Issue by gtoal** [amaiorano/vectrexy#6]
Vectrexy v0.0.0-720-gb68337f breaks into the debugger on running the DAC offset test.

[Unsupported] ShiftRegisterMode expected to only support ShiftOutUnder02
Exception caught:
Assertion Failed!
 Condition: AuxCntl::GetTimer2Mode(value) == TimerMode::OneShot
 File: D:\a\vectrexy\vectrexy\libs\emulator\src\Via.cpp(435)
 Message: t2 assumed always on one-shot mode

[$0190] d70b       STB $0b                          DP:(PC) = $d00b $d00b<-$b6                0 A$1f|B$b6|X$fbb4|Y$0000|U$01f0|S$cbe8|DP$d0|eFHInzvc
*[$0192] 4a         DECA                                                                       (step)>

By the way it would be useful to put the Vectrexy version number in the Help/About Vectrexy box as the only place it can be found is in the window title which is text that cannot be cut & pasted in Windows.

The test rom code can be seen at https://gtoal.com/vectrex/disassemblies/TestRev4.asm

L018B               LDD   #$1FB6                  ; 018B: CC 1F B6
                    STA   <VIA_port_b             ; 018E: 97 00
                    STB   <VIA_aux_cntl           ; 0190: D7 0B
                    DECA                          ; 0192: 4A
                    BSR   L01BE                   ; 0193: 8D 29

**Comment by amaiorano** [comment]
Thanks, Graham, I'll try to take a look at this asap. Glad to know you're still testing out my emulator.

**Comment by gtoal** [comment]
I use it regularly. It's my go-to emulator of choice on Windows.

**Comment by amaiorano** [comment]
> Vectrexy v0.0.0-720-gb68337f breaks into the debugger on running the DAC offset test.

This has been fixed. It will no longer break, but just report a message for the unsupported timer mode.

> By the way it would be useful to put the Vectrexy version number in the Help/About Vectrexy box as the only place it can be found is in the window title which is text that cannot be cut & pasted in Windows.

Fixed this as well, although I'm not able to copy from the About dialog...

**Comment by amaiorano** [comment]
Graham, when you have a chance, can you confirm that this works for you?
