### ISSUE TITLE
Veccy Pong v092: device access causes vectrexy to break into debugger/monitor

### ISSUE THREAD

**Issue by gtoal** [amaiorano/vectrexy#9]
https://forums.atariage.com/topic/358506-how-to-turn-your-xmas-tree-into-a-vectrex-game/

It accesses a pin to control an LED; also tries to save highscore.  One of these must be blowing up Vectrexy.

G

**Comment by amaiorano** [comment]
Hi Graham,

Thanks for reporting this. I fixed the issue, and Vectrexy is now able to play Veccy Pong v092. You can grab the latest version on the [main page here](https://github.com/amaiorano/vectrexy?tab=readme-ov-file#build-status-).

**Comment by amaiorano** [comment]
Reopening until you can confirm that it's working for you as well.

**Comment by gtoal** [comment]
Yes, it's working now! Thanks.

**Comment by amaiorano** [comment]
Great, thanks!
